name: Auto comment on label

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if labeled with "need help"
        if: ${{ github.event.label.name == 'need help' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: "Thank you for adding the 'need help' label to this issue. We will try our best to provide assistance as soon as possible."
          issue-number: ${{ github.event.issue.number }}
        
      - name: Check if labeled with "need demo"
        if: ${{ github.event.label.name == 'need demo' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body-path: "/.github/workflows/issue_comment_template/need_demo.md"
          issue-number: ${{ github.event.issue.number }}

      - name: Check if labeled with "bug"
        if: ${{ github.event.label.name == 'bug' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: "Thank you for reporting this issue. We will investigate and fix the issue as soon as possible."
          issue-number: ${{ github.event.issue.number }}

    
