name: Auto comment on label

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if labeled with "need help"
        if: ${{ github.event.label.name == 'need help' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: |
            ## Welcome to solve the current problem / 当前问题需要你的帮助
            Welcome to solve the current problem, thank you very much.
            欢迎来解决当前问题，不胜感激
          issue-number: ${{ github.event.issue.number }}
        
      - name: Check if labeled with "need demo"
        if: ${{ github.event.label.name == 'need demo' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: |
            ## please provide a demo as soon as possible / 请尽快提供一个可复现 demo
            In order for us to reproduce and fix the problem more efficiently and conveniently, please provide a minimal demo, thank you very much.
            为了让我们更高效方便的重现和修复问题，请提供一个最小的 demo，非常感谢。
          issue-number: ${{ github.event.issue.number }}

      - name: Check if labeled with "bug"
        if: ${{ github.event.label.name == 'bug' }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          body: |
            ## The current problem will be fixed as soon as possible / 当前问题会尽快修复
            Related problems have been tried to reappear, and related problems will be fixed as soon as possible. Similarly, you are welcome to contribute code to fix the current problems.
            相关问题已尝试复现，相关问题会尽快修复，同样欢迎贡献代码修复当前问题。
          issue-number: ${{ github.event.issue.number }}

    
