name: Auto comment on label

on:
  issues:
    types: [labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check if labeled with "tag1"
        run: |
          if [ "${{ github.event.label.name }}" != "tag1" ]; then
            exit 0
          fi
        shell: bash
        continue-on-error: true
        
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for adding "tag1" to this issue!
